/**
 * Compressed codecs: FLAC, Vorbis, AAC and ALAC.
 *
 * The fixtures are generated by `tests/assets/generate-audio-fixtures.ts` and
 * committed, so the suite needs no ffmpeg — the same arrangement as the KTX2
 * fixtures. Each is one second of a **known** stereo tone: 480 Hz left, 960 Hz
 * right, at 48 kHz, encoded from a 16-bit WAV.
 *
 * ## Why synthetic content here and real content in audio-real-files.test.ts
 *
 * They catch different things and neither replaces the other.
 *
 * The MP3 there is real music, so it can only support weak claims — "not
 * silent", "the channels differ". These files carry a signal whose exact
 * spectrum is known, so `goertzel` can ask the question that actually matters:
 * *did 480 Hz come back at 480 Hz, in the left channel and not the right?* A
 * decoder that swapped channels, misreported the sample rate, or de-interleaved
 * with the wrong stride fails that and passes every level-based check, because
 * all three produce a buffer of the right length full of plausible floats.
 *
 * What both tiers share is the property that matters most: **a real encoder
 * made these files.** libFLAC, libvorbis and ffmpeg's AAC and ALAC encoders
 * were not written to make this crate's tests pass.
 *
 * ## The reference is rebuilt here, not committed
 *
 * The expected samples come from re-synthesising the generator's source WAV with
 * the same constants. That couples this file to
 * `generate-audio-fixtures.ts` — **if you change the tone there, change it
 * here** — and buys the strongest assertion in the audio suite: FLAC and ALAC
 * are lossless, so their decoded output must be *bit-identical* to the WAV's,
 * not merely close.
 */

import { describe, expect, test } from "bun:test"
import { join } from "node:path"

import { decodeAudioClip, inspectAudioFile, loadAudioClip } from "../index.js"
import { goertzel, interleave, maxAbsDiff, peak, sine, stereo } from "./helpers/dsp.js"
import { buildWav } from "./helpers/wav-build.js"

// Must match generate-audio-fixtures.ts.
const RATE = 48_000
const FRAMES = 48_000
const TONE_L = 480
const TONE_R = 960
const AMPLITUDE = 0.5

const ASSETS = join(import.meta.dir, "assets")

interface Case {
  file: string
  container: string
  codec: string
  /** Lossless codecs must reproduce the source exactly. */
  lossless: boolean
  /**
   * Amplitude tolerance for the recovered tones.
   *
   * Never zero, even for a lossless codec: the *source* is 16-bit, so the
   * analytic 0.5 is quantised before any encoder sees it and comes back about
   * 1.3e-6 off. Bit-exactness against the source is a different assertion and
   * has its own test — this one is about the signal, not the bytes.
   */
  tolerance: number
  /**
   * Frames the decoder actually returns. Equal to the source for everything
   * except AAC — see the note on that case below.
   */
  frames: number
  /**
   * Whether the decoded output starts at the same sample as the source. False
   * for AAC, whose untrimmed encoder delay shifts everything, making a
   * sample-wise comparison meaningless there.
   */
  aligned: boolean
}

const CASES: Case[] = [
  { file: "tone.flac", container: "flac", codec: "flac", lossless: true, tolerance: 1e-4, frames: FRAMES, aligned: true },
  { file: "tone.ogg", container: "ogg", codec: "vorbis", lossless: false, tolerance: 0.01, frames: FRAMES, aligned: true },
  {
    file: "tone-aac.m4a",
    container: "isomp4",
    codec: "aac",
    lossless: false,
    tolerance: 0.02,
    // **Three numbers disagree for AAC, and only for AAC.** The source is
    // 48000 frames; the container's header says 49024; the decoder returns
    // 49152 (= 48 x 1024, whole AAC frames). symphonia is asked for gapless
    // decoding (`AudioDecoderOptions::default()`) and it trims MP3, Vorbis and
    // ALAC to the exact source length — but not AAC-in-MP4.
    //
    // The practical effect is a chunk of encoder delay left at the head, so an
    // AAC asset starts slightly late: irrelevant for music, potentially
    // audible for a sound effect triggered on a frame.
    //
    // **How much delay is deliberately not asserted anywhere.** It cannot be
    // measured with this fixture: the tone repeats every 100 samples, so
    // cross-correlation only determines the offset modulo 100, and a search
    // over it returns whichever multiple happened to score best (1724 when
    // measured, which is 1024 mod 100 — consistent with a 1024-sample delay
    // but not evidence of one). Measuring it properly needs an aperiodic
    // fixture such as an impulse or a sweep. Stating a number here would be
    // documenting a guess.
    //
    // Pinned rather than papered over: if this is fixed upstream, this test
    // fails, which is the point.
    frames: 49_152,
    aligned: false,
  },
  { file: "tone-alac.m4a", container: "isomp4", codec: "alac", lossless: true, tolerance: 1e-4, frames: FRAMES, aligned: true },
]

/** The exact samples the fixtures were encoded from. */
function referenceWav(): Uint8Array {
  return buildWav({
    samples: interleave([
      sine(TONE_L, RATE, FRAMES, AMPLITUDE),
      sine(TONE_R, RATE, FRAMES, AMPLITUDE),
    ]),
    sampleRate: RATE,
    channels: 2,
    encoding: "s16",
  })
}

describe.each(CASES)("$file", (c) => {
  const path = join(ASSETS, c.file)

  test("header reports the container and codec", async () => {
    const info = await inspectAudioFile(path)
    expect(info.container).toBe(c.container)
    expect(info.codec).toBe(c.codec)
    expect(info.sampleRate).toBe(RATE)
    expect(info.channels).toBe(2)
  })

  test("decodes to the expected shape", async () => {
    const clip = await loadAudioClip(path)
    expect(clip.sampleRate).toBe(RATE)
    expect(clip.channels).toBe(2)
    expect(clip.frameCount).toBe(c.frames)
  })

  test("each channel carries its own tone and not the other's", async () => {
    const clip = await loadAudioClip(path)
    const [l, r] = stereo(clip.getSamples())

    // The assertion this whole file exists for. Amplitude alone would pass with
    // the channels swapped; asking each channel for the tone it should *not*
    // have is what makes the stereo layout observable.
    //
    // Frequency content is also the right tool here for a second reason: it is
    // insensitive to a head offset, so it states the same thing about AAC —
    // whose output is shifted — as about the codecs that align exactly.
    expect(Math.abs(goertzel(l, RATE, TONE_L) - AMPLITUDE)).toBeLessThanOrEqual(c.tolerance)
    expect(goertzel(l, RATE, TONE_R)).toBeLessThan(0.01)

    expect(Math.abs(goertzel(r, RATE, TONE_R) - AMPLITUDE)).toBeLessThanOrEqual(c.tolerance)
    expect(goertzel(r, RATE, TONE_L)).toBeLessThan(0.01)
  })

  test("stays within full scale", async () => {
    const clip = await loadAudioClip(path)
    const samples = clip.getSamples()
    expect(peak(samples)).toBeLessThanOrEqual(1.0)
    expect(samples.every((s) => Number.isFinite(s))).toBe(true)
  })

  test("decoding twice gives identical samples", async () => {
    const a = await loadAudioClip(path)
    const b = await loadAudioClip(path)
    expect(maxAbsDiff(a.getSamples(), b.getSamples())).toBe(0)
  })

  if (c.lossless) {
    test("is bit-identical to the source it was encoded from", async () => {
      // The strongest assertion in the audio suite, and only available here:
      // lossless means "close" is not good enough, so any deviation at all —
      // a rounding difference in the sample conversion, a dropped sample, a
      // half-frame offset — fails on the first differing sample.
      const reference = await decodeAudioClip(referenceWav())
      const clip = await loadAudioClip(path)
      expect(clip.frameCount).toBe(reference.frameCount)
      expect(maxAbsDiff(clip.getSamples(), reference.getSamples())).toBe(0)
    })
  } else if (c.aligned) {
    test("is close to the source without being identical to it", async () => {
      const reference = await decodeAudioClip(referenceWav())
      const clip = await loadAudioClip(path)

      const n = Math.min(clip.getSamples().length, reference.getSamples().length)
      const got = clip.getSamples().subarray(0, n)
      const want = reference.getSamples().subarray(0, n)

      // Lossy, so this is a band rather than a point. The upper bound catches a
      // broken decode; the lower bound is the interesting half — a difference of
      // exactly zero would mean the fixture is not actually lossy, i.e. someone
      // regenerated it with the wrong codec.
      const diff = maxAbsDiff(got, want)
      expect(diff).toBeGreaterThan(0)
      expect(diff).toBeLessThan(0.15)
    })
  } else {
    test("does not align with the source, and that is the known AAC deviation", async () => {
      const reference = await decodeAudioClip(referenceWav())
      const clip = await loadAudioClip(path)

      // Documenting the deviation rather than skipping it. Compared from sample
      // zero the difference is enormous — near twice the amplitude, because a
      // shifted sine is compared against an unshifted one and they end up out of
      // phase. That is *not* a decode failure, and the frequency-domain test
      // above is what establishes the content is right.
      //
      // This assertion exists so that if the head delay is ever trimmed
      // upstream, this file fails loudly and someone re-reads the note on the
      // AAC case rather than quietly inheriting a different behaviour.
      const n = Math.min(clip.getSamples().length, reference.getSamples().length)
      const diff = maxAbsDiff(clip.getSamples().subarray(0, n), reference.getSamples().subarray(0, n))
      expect(diff).toBeGreaterThan(0.5)
    })
  }
})

describe("across codecs", () => {
  test("every codec recovers the same pitch content", async () => {
    for (const c of CASES) {
      const clip = await loadAudioClip(join(ASSETS, c.file))
      const [l, r] = stereo(clip.getSamples())
      expect(goertzel(l, RATE, TONE_L)).toBeCloseTo(AMPLITUDE, 1)
      expect(goertzel(r, RATE, TONE_R)).toBeCloseTo(AMPLITUDE, 1)
    }
  })

  test("the two lossless codecs agree with each other exactly", async () => {
    // FLAC and ALAC are independent implementations of the same promise. If
    // they agree bit-for-bit, both round trips are almost certainly right; if
    // only one matched the reference, the reference would be the suspect.
    const flac = await loadAudioClip(join(ASSETS, "tone.flac"))
    const alac = await loadAudioClip(join(ASSETS, "tone-alac.m4a"))
    expect(maxAbsDiff(flac.getSamples(), alac.getSamples())).toBe(0)
  })

  test("the same MP4 container serves two different codecs", async () => {
    // tone-aac.m4a and tone-alac.m4a are both isomp4. Track selection and codec
    // dispatch have to come from the sample entry, not from the file extension
    // — this fails if the container's codec is inferred from the container.
    const aac = await inspectAudioFile(join(ASSETS, "tone-aac.m4a"))
    const alac = await inspectAudioFile(join(ASSETS, "tone-alac.m4a"))
    expect(aac.container).toBe(alac.container)
    expect(aac.codec).not.toBe(alac.codec)
  })
})
