// Coverage for `loadKtx2Texture` — the block-compressed loader.
//
// **Two tiers of fixture, on purpose.**
//
// 1. The **inline writer** below builds KTX2 files byte by byte. It exists for
//    the edge and failure cases no real encoder would produce on request —
//    truncated levels, cubemaps, BasisLZ payloads, unaligned dimensions — and
//    it puts the exact bytes going in next to the values asserted coming out,
//    the same reasoning as the TGA/HDR fixtures in image-formats.test.ts.
// 2. The **`quad-*.ktx2` files** in `tests/assets/` are genuine KTX-Software
//    v4.4.2 output, checked in, regenerated by
//    `tests/assets/generate-ktx2-fixtures.ts`. They prove the inline writer's
//    assumptions match reality (DFD contents, level ordering as actually
//    emitted, mip padding), and because their contents are known they are what
//    the pixel assertions run against.
//
// **What each tier can and cannot catch.** The block math is the whole risk in
// this loader: `bytes_per_row` counts blocks, not pixels, so a BC7 row is
// `ceil(w/4) * 16` and not `w * 4`. Getting that wrong does *not* throw — wgpu
// reports it as a validation error, and this binding does not surface those as
// exceptions (see "Debugging WebGPU validation errors" in CLAUDE.md). So every
// successful-load test wraps the call in an error scope and asserts the scope
// came back empty. Without that, a wrong stride would still produce a texture
// handle with the right dimensions and the suite would be green.
//
// But an error scope only proves wgpu accepted the upload — not that the bytes
// landed in the right place. Nothing in tier 1 ever looks at a texel, so it
// cannot see mip levels swapped or a level offset by a block. That is what the
// tier-2 pixel tests at the bottom of this file are for.
//
// The `12x4` case in tier 1 is the most load-bearing of the structural ones:
// non-square, with a mip tail below the 4x4 block size, which is exactly where a
// `ceil` written as a truncating divide, or a logical extent used where the
// physical one is required, goes wrong.
import { beforeAll, describe, expect, it } from "bun:test";
import { zstdCompressSync } from "node:zlib";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
    type GpuAdapter,
    type GpuDevice,
    GPUTextureUsage,
    loadKtx2Texture,
    requestAdapter,
} from "../index.js";
import { createTextureRenderer, pixelAt } from "./helpers/texture-render.js";

// ── KTX2 fixture writer ─────────────────────────────────────────────────────
//
// Layout (KTX2 spec §3):
//   0..80            header + index
//   80..80+24*N      level index, one 24-byte entry per mip, level 0 first
//   then             the DFD section
//   then             level data
//
// Level *data* is written smallest-mip-first, which is what the `ktx` tool
// emits (it streams the small levels early). The index still lists level 0
// first. That mismatch is deliberate: a loader that walked the file in storage
// order instead of following the index would read the mip chain upside down and
// this fixture would catch it.

/** VkFormat values, matching `ktx2::Format`. */
const VK = {
    UNDEFINED: 0,
    BC1_RGBA_UNORM_BLOCK: 133,
    BC5_UNORM_BLOCK: 141,
    BC7_UNORM_BLOCK: 145,
    BC7_SRGB_BLOCK: 146,
    ASTC_4x4_UNORM_BLOCK: 157,
} as const;

const SUPERCOMPRESSION = { NONE: 0, BASIS_LZ: 1, ZSTD: 2, ZLIB: 3 } as const;

const KTX2_MAGIC = [0xab, 0x4b, 0x54, 0x58, 0x20, 0x32, 0x30, 0xbb, 0x0d, 0x0a, 0x1a, 0x0a];

/**
 * A minimal but structurally valid Basic Data Format Descriptor.
 *
 * The loader never reads the DFD — it takes the format from the header's
 * `vkFormat` — but `ktx2::Reader::new` parses and validates the section, so a
 * file without one is rejected before the loader sees it. Hence a real block
 * rather than zero padding: 8-byte block header, 16 fixed bytes, one 16-byte
 * sample.
 */
function basicDfd(blockBytes: number, blockW: number, blockH: number, srgb: boolean): Uint8Array {
    const SAMPLES = 1;
    const size = 8 + 16 + 16 * SAMPLES; // 40
    const dfd = new Uint8Array(size);
    const view = new DataView(dfd.buffer);

    // Block header: vendorId 0 | descriptorType 0, version 2, size.
    view.setUint32(0, 0, true);
    view.setUint16(4, 2, true);
    view.setUint16(6, size, true);

    dfd[8] = 0; // colorModel (unspecified — not read by the loader)
    dfd[9] = 1; // colorPrimaries: BT709
    dfd[10] = srgb ? 2 : 1; // transferFunction: 2 = sRGB, 1 = linear
    dfd[11] = 0; // flags
    // texelBlockDimension is stored as (dimension - 1).
    dfd[12] = blockW - 1;
    dfd[13] = blockH - 1;
    dfd[14] = 0;
    dfd[15] = 0;
    dfd[16] = blockBytes; // bytesPlane0
    return dfd;
}

interface Ktx2Spec {
    vkFormat: number;
    width: number;
    height: number;
    /** Raw (uncompressed) bytes for each mip, level 0 first. */
    levels: Uint8Array[];
    blockBytes: number;
    blockW: number;
    blockH: number;
    srgb?: boolean;
    supercompression?: number;
    layerCount?: number;
    faceCount?: number;
    pixelDepth?: number;
}

function buildKtx2(spec: Ktx2Spec): Uint8Array {
    const scheme = spec.supercompression ?? SUPERCOMPRESSION.NONE;
    const levelCount = spec.levels.length;

    // Supercompressed levels are stored compressed; `uncompressedByteLength`
    // still reports the original size.
    const stored = spec.levels.map((raw) =>
        scheme === SUPERCOMPRESSION.ZSTD ? new Uint8Array(zstdCompressSync(raw)) : raw,
    );

    const dfd = basicDfd(spec.blockBytes, spec.blockW, spec.blockH, spec.srgb ?? false);
    const levelIndexBytes = levelCount * 24;
    const dfdOffset = 80 + levelIndexBytes;
    const dfdByteLength = 4 + dfd.length; // 4-byte total-length field, then the block
    let cursor = dfdOffset + dfdByteLength;

    // Assign data offsets smallest-mip-first (see the note above).
    const offsets = new Array<number>(levelCount).fill(0);
    for (let i = levelCount - 1; i >= 0; i--) {
        offsets[i] = cursor;
        cursor += (stored[i] as Uint8Array).length;
    }

    const out = new Uint8Array(cursor);
    const view = new DataView(out.buffer);
    out.set(KTX2_MAGIC, 0);

    view.setUint32(12, spec.vkFormat, true);
    view.setUint32(16, 1, true); // typeSize: must be 1 for block-compressed formats
    view.setUint32(20, spec.width, true);
    view.setUint32(24, spec.height, true);
    view.setUint32(28, spec.pixelDepth ?? 0, true);
    view.setUint32(32, spec.layerCount ?? 0, true);
    view.setUint32(36, spec.faceCount ?? 1, true);
    view.setUint32(40, levelCount, true);
    view.setUint32(44, scheme, true);

    // Index: dfd offset/length, kvd offset/length (u32), sgd offset/length (u64).
    view.setUint32(48, dfdOffset, true);
    view.setUint32(52, dfdByteLength, true);
    view.setUint32(56, 0, true); // no key/value data
    view.setUint32(60, 0, true);
    view.setBigUint64(64, 0n, true); // no supercompression global data
    view.setBigUint64(72, 0n, true);

    for (let i = 0; i < levelCount; i++) {
        const base = 80 + i * 24;
        view.setBigUint64(base, BigInt(offsets[i] as number), true);
        view.setBigUint64(base + 8, BigInt((stored[i] as Uint8Array).length), true);
        view.setBigUint64(base + 16, BigInt((spec.levels[i] as Uint8Array).length), true);
    }

    view.setUint32(dfdOffset, dfdByteLength, true); // DFD total length field
    out.set(dfd, dfdOffset + 4);
    for (let i = 0; i < levelCount; i++) out.set(stored[i] as Uint8Array, offsets[i] as number);
    return out;
}

const mipSize = (base: number, level: number) => Math.max(1, base >> level);

/** Number of mips in a full chain down to 1x1. */
function fullMipCount(w: number, h: number): number {
    return Math.floor(Math.log2(Math.max(w, h))) + 1;
}

/**
 * Correctly-sized (but not meaningfully encoded) block payloads for a full mip
 * chain. The bytes are a counter, not a real BC encoding — nothing here samples
 * the texture, so what matters is that the *size* of every level is exactly what
 * the block layout demands.
 */
function mipChain(w: number, h: number, blockBytes: number, blockW: number, blockH: number, count?: number): Uint8Array[] {
    const n = count ?? fullMipCount(w, h);
    const levels: Uint8Array[] = [];
    for (let i = 0; i < n; i++) {
        const lw = mipSize(w, i);
        const lh = mipSize(h, i);
        const blocks = Math.ceil(lw / blockW) * Math.ceil(lh / blockH);
        const data = new Uint8Array(blocks * blockBytes);
        for (let b = 0; b < data.length; b++) data[b] = (b + i) & 0xff;
        levels.push(data);
    }
    return levels;
}

const BC7 = { blockBytes: 16, blockW: 4, blockH: 4 };
const BC5 = { blockBytes: 16, blockW: 4, blockH: 4 };
const BC1 = { blockBytes: 8, blockW: 4, blockH: 4 };

// ── setup ───────────────────────────────────────────────────────────────────

let adapter: GpuAdapter | null = null;
let device: GpuDevice | null = null;
/** A device deliberately created *without* texture-compression-bc. */
let plainDevice: GpuDevice | null = null;
let hasBc = false;
let dir = "";

beforeAll(async () => {
    dir = mkdtempSync(join(tmpdir(), "ktx2-"));
    adapter = await requestAdapter();
    if (!adapter) return;
    hasBc = adapter.features.has("texture-compression-bc");
    if (hasBc) {
        device = await adapter.requestDevice({
            label: "ktx2-test",
            requiredFeatures: ["texture-compression-bc"],
        });
    }
    plainDevice = await adapter.requestDevice({ label: "ktx2-test-no-bc" });
});

function write(name: string, bytes: Uint8Array): string {
    const path = join(dir, name);
    writeFileSync(path, bytes);
    return path;
}

/**
 * Loads and fails if wgpu complained.
 *
 * This is the load-bearing part of every success-path test: a wrong
 * `bytes_per_row` produces a valid-looking `GpuTexture` and a validation error
 * that nothing would otherwise observe.
 *
 * **This used to wrap the load in `pushErrorScope`/`popErrorScope`, and that
 * stopped working in the wgpu 30 upgrade.** wgpu 30 made error scopes
 * thread-local, and `loadKtx2Texture` does its GPU work inside an
 * `AsyncTask::compute` on a libuv worker — so a scope opened here, on the JS
 * thread, could not see it. The pop returned `null` unconditionally and every
 * assertion below it was vacuous while staying green.
 *
 * The loader now brackets its own GPU work in a scope on the worker thread and
 * rejects the promise (see `gpu::error::with_validation_scope`), so an
 * unobserved validation error becomes a failed `await` right here. Nothing to
 * remember to wrap; `loadGpuValidationRejects` below pins that it really fires.
 */
async function loadChecked(dev: GpuDevice, path: string) {
    return await loadKtx2Texture(dev, path);
}

describe("loadKtx2Texture", () => {
    it("loads a mipped BC7 texture, reporting format and mip count from the file", async () => {
        if (!device) return;
        const levels = mipChain(64, 64, BC7.blockBytes, BC7.blockW, BC7.blockH);
        const path = write("bc7.ktx2", buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 64, height: 64, levels, ...BC7 }));

        const texture = await loadChecked(device, path);
        expect(texture.width).toBe(64);
        expect(texture.height).toBe(64);
        expect(texture.format).toBe("bc7-rgba-unorm");
        expect(texture.mipLevelCount).toBe(7); // 64,32,16,8,4,2,1
    });

    it("maps the sRGB block format to the -srgb texture format", async () => {
        if (!device) return;
        const levels = mipChain(16, 16, BC7.blockBytes, BC7.blockW, BC7.blockH);
        const path = write(
            "bc7-srgb.ktx2",
            buildKtx2({ vkFormat: VK.BC7_SRGB_BLOCK, width: 16, height: 16, levels, srgb: true, ...BC7 }),
        );
        const texture = await loadChecked(device, path);
        // The colour space comes from the file — there is no caller-side option
        // to contradict it, unlike loadImageTexture's `colorSpace`.
        expect(texture.format).toBe("bc7-rgba-unorm-srgb");
    });

    it("loads BC5 (the normal-map format) and BC1 (the 4bpp format)", async () => {
        if (!device) return;
        const bc5 = write(
            "bc5.ktx2",
            buildKtx2({
                vkFormat: VK.BC5_UNORM_BLOCK,
                width: 32,
                height: 32,
                levels: mipChain(32, 32, BC5.blockBytes, BC5.blockW, BC5.blockH),
                ...BC5,
            }),
        );
        expect((await loadChecked(device, bc5)).format).toBe("bc5-rg-unorm");

        // BC1 has 8-byte blocks rather than 16 — if block size were hardcoded
        // anywhere, this is what would catch it.
        const bc1 = write(
            "bc1.ktx2",
            buildKtx2({
                vkFormat: VK.BC1_RGBA_UNORM_BLOCK,
                width: 32,
                height: 32,
                levels: mipChain(32, 32, BC1.blockBytes, BC1.blockW, BC1.blockH),
                ...BC1,
            }),
        );
        expect((await loadChecked(device, bc1)).format).toBe("bc1-rgba-unorm");
    });

    it("handles a non-square texture whose mip tail is smaller than one block", async () => {
        if (!device) return;
        // 12x4 is deliberately awkward while still legal: non-square, and the
        // chain runs 12x4, 6x2, 3x1, 1x1 — so every level after the first is
        // smaller than a 4x4 block in at least one axis and has to be uploaded
        // at its *physical* (block-rounded) extent rather than its logical size.
        // Getting that wrong fails only on these tail levels, which is why this
        // case exists separately from the square ones.
        const levels = mipChain(12, 4, BC7.blockBytes, BC7.blockW, BC7.blockH);
        expect(levels.length).toBe(4);
        expect((levels[0] as Uint8Array).length).toBe(3 * 1 * 16); // ceil(12/4)=3, ceil(4/4)=1
        expect((levels[3] as Uint8Array).length).toBe(16); // 1x1 still occupies a whole block

        const path = write("odd.ktx2", buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 12, height: 4, levels, ...BC7 }));
        const texture = await loadChecked(device, path);
        expect(texture.width).toBe(12);
        expect(texture.height).toBe(4);
        expect(texture.mipLevelCount).toBe(4);
    });

    it("transparently decompresses zstd supercompression", async () => {
        if (!device) return;
        const levels = mipChain(32, 32, BC7.blockBytes, BC7.blockW, BC7.blockH);
        const plain = buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 32, height: 32, levels, ...BC7 });
        const zstd = buildKtx2({
            vkFormat: VK.BC7_UNORM_BLOCK,
            width: 32,
            height: 32,
            levels,
            supercompression: SUPERCOMPRESSION.ZSTD,
            ...BC7,
        });
        // Sanity-check the fixture itself actually compressed — the counter
        // payload is highly compressible, so a same-size file would mean the
        // zstd branch of the writer silently did nothing.
        expect(zstd.length).toBeLessThan(plain.length);

        const texture = await loadChecked(device, write("zstd.ktx2", zstd));
        expect(texture.width).toBe(32);
        expect(texture.format).toBe("bc7-rgba-unorm");
        expect(texture.mipLevelCount).toBe(6);
    });

    it("accepts a single-level file with no mip chain", async () => {
        if (!device) return;
        const levels = mipChain(8, 8, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const path = write("single.ktx2", buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 8, height: 8, levels, ...BC7 }));
        expect((await loadChecked(device, path)).mipLevelCount).toBe(1);
    });
});

describe("loadKtx2Texture rejections", () => {
    // Every case here must reject the promise. The bar is not just "fails" but
    // "fails as a catchable JS error": a panic in the Rust worker would abort
    // the process instead, taking the test runner with it, so these double as
    // panic regression tests.

    it("rejects a truncated mip level rather than uploading garbage", async () => {
        if (!device) return;
        const levels = mipChain(32, 32, BC7.blockBytes, BC7.blockW, BC7.blockH);
        const short = levels[2] as Uint8Array;
        levels[2] = short.slice(0, short.length - 16); // one block short
        const path = write("truncated.ktx2", buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 32, height: 32, levels, ...BC7 }));
        expect(loadKtx2Texture(device, path)).rejects.toThrow(/truncated/i);
    });

    it("rejects a Basis Universal payload, naming the transcode requirement", async () => {
        if (!device) return;
        // vkFormat 0 (VK_FORMAT_UNDEFINED) is how KTX2 marks a universal payload.
        const levels = mipChain(16, 16, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const path = write(
            "basis.ktx2",
            buildKtx2({ vkFormat: VK.UNDEFINED, width: 16, height: 16, levels, supercompression: SUPERCOMPRESSION.BASIS_LZ, ...BC7 }),
        );
        expect(loadKtx2Texture(device, path)).rejects.toThrow(/transcode/i);
    });

    it("rejects ZLIB supercompression", async () => {
        if (!device) return;
        const levels = mipChain(16, 16, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const path = write(
            "zlib.ktx2",
            buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 16, height: 16, levels, supercompression: SUPERCOMPRESSION.ZLIB, ...BC7 }),
        );
        expect(loadKtx2Texture(device, path)).rejects.toThrow(/supercompression/i);
    });

    it("rejects cubemaps, texture arrays and 3D textures", async () => {
        if (!device) return;
        const levels = mipChain(16, 16, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const base = { vkFormat: VK.BC7_UNORM_BLOCK, width: 16, height: 16, levels, ...BC7 };

        const cube = write("cube.ktx2", buildKtx2({ ...base, faceCount: 6 }));
        expect(loadKtx2Texture(device, cube)).rejects.toThrow(/cubemap/i);

        const array = write("array.ktx2", buildKtx2({ ...base, layerCount: 4 }));
        expect(loadKtx2Texture(device, array)).rejects.toThrow(/array/i);

        const volume = write("3d.ktx2", buildKtx2({ ...base, pixelDepth: 4 }));
        expect(loadKtx2Texture(device, volume)).rejects.toThrow(/3D/i);
    });

    it("rejects base dimensions that are not a multiple of the block size", async () => {
        if (!device) return;
        // WebGPU will not create a block-compressed texture whose base extent is
        // unaligned, so this has to be caught rather than worked around — there
        // is no pixel data to invent for the partial block. Encoders pad; an
        // unaligned file is a bad asset.
        const levels = mipChain(13, 7, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const path = write("unaligned.ktx2", buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 13, height: 7, levels, ...BC7 }));
        expect(loadKtx2Texture(device, path)).rejects.toThrow(/not a multiple of/i);
    });

    it("rejects a format it does not map, pointing at the BC family", async () => {
        if (!device) return;
        const levels = mipChain(16, 16, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const path = write(
            "astc.ktx2",
            buildKtx2({ vkFormat: VK.ASTC_4x4_UNORM_BLOCK, width: 16, height: 16, levels, ...BC7 }),
        );
        expect(loadKtx2Texture(device, path)).rejects.toThrow(/BC/);
    });

    it("rejects a file that is not KTX2 at all", async () => {
        if (!device) return;
        const path = write("nope.ktx2", new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]));
        expect(loadKtx2Texture(device, path)).rejects.toThrow(/not a valid KTX2/i);
    });

    it("rejects a missing file", async () => {
        if (!device) return;
        expect(loadKtx2Texture(device, join(dir, "does-not-exist.ktx2"))).rejects.toThrow(/failed to read/i);
    });

    it("rejects with an actionable error when the device lacks texture-compression-bc", async () => {
        if (!plainDevice) return;
        // The whole point of the feature gate: there is no software fallback for
        // block-compressed data, so this must be a clear error rather than a
        // broken handle. `plainDevice` was created without requiredFeatures.
        expect(plainDevice.features.has("texture-compression-bc")).toBe(false);

        const levels = mipChain(16, 16, BC7.blockBytes, BC7.blockW, BC7.blockH, 1);
        const path = write("gate.ktx2", buildKtx2({ vkFormat: VK.BC7_UNORM_BLOCK, width: 16, height: 16, levels, ...BC7 }));
        expect(loadKtx2Texture(plainDevice, path)).rejects.toThrow(/texture-compression-bc/);
    });
});

// ── Real KTX-Software fixtures, with pixel assertions ───────────────────────
//
// Everything above asserts on structure: dimensions, format, mip count, and an
// empty validation error scope. None of it looks at a single texel, so none of
// it can catch the loader putting the right number of correct-sized bytes in the
// *wrong place* — mip levels swapped, or a level offset by a block. These tests
// close that by sampling the texture through a render pass (`readTexturePixels`
// rejects BC formats by design) and checking the colours that come back.
//
// The assertions are **exact**, not approximate. BC is lossy in general, but a
// 4x4 block of one uniform colour is something BC7/BC5/BC1 all represent
// exactly, so the fixture's block-aligned solid quadrants survive the round trip
// bit-for-bit — measured, not assumed. Exactness is what makes these strong: a
// tolerance wide enough to absorb real encoder error would also absorb a
// half-block offset.

const ASSETS = join(import.meta.dir, "assets");

describe("GPU-side validation errors reach the caller", () => {
    // The regression these guard against is specific and was live for exactly
    // one commit: wgpu 30's error scopes are thread-local, so a scope opened on
    // the JS thread cannot see work done inside `AsyncTask::compute` on a libuv
    // worker. Everything below happens on that worker.
    //
    // Both tests pass a *well-formed* file. The failure is raised by wgpu at
    // `create_texture`, not by any of this crate's own CPU-side checks — which
    // is the point, because CPU-side rejections were never affected.
    //
    // Mutation check: remove `with_validation_scope` from `LoadKtx2Task` and
    // both of these fail, while every other test in this file still passes.

    it("rejects when wgpu refuses the texture, instead of returning a broken one", async () => {
        if (!device) return;
        // STORAGE_BINDING is not allowed on block-compressed formats. Nothing
        // on the CPU side checks usage bits, so this reaches wgpu.
        const load = loadKtx2Texture(device, join(ASSETS, "quad-bc7.ktx2"), {
            usage: GPUTextureUsage.TEXTURE_BINDING
                | GPUTextureUsage.COPY_DST
                | GPUTextureUsage.STORAGE_BINDING,
        });
        await expect(load).rejects.toThrow(/STORAGE_BINDING/);
    });

    it("names the failing operation in the rejection", async () => {
        if (!device) return;
        // A bare "Validation Error" gives no clue which of a frame's many async
        // loads produced it, so the operation and path are prefixed.
        const load = loadKtx2Texture(device, join(ASSETS, "quad-bc7.ktx2"), {
            usage: GPUTextureUsage.TEXTURE_BINDING
                | GPUTextureUsage.COPY_DST
                | GPUTextureUsage.STORAGE_BINDING,
        });
        await expect(load).rejects.toThrow(/loadKtx2Texture\('.*quad-bc7\.ktx2'\)/);
    });

    it("still resolves normally when the usage flags are legal", async () => {
        if (!device) return;
        const texture = await loadKtx2Texture(device, join(ASSETS, "quad-bc7.ktx2"), {
            usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST,
        });
        expect(texture.format).toBe("bc7-rgba-unorm");
        expect(texture.usage & GPUTextureUsage.STORAGE_BINDING).toBe(0);
    });
});

const Q = 64; // fixture dimensions

/** Quadrant sample points, away from edges so nearest-sampling is unambiguous. */
const QUADRANT = {
    topLeft: [16, 16],
    topRight: [48, 16],
    bottomLeft: [16, 48],
    bottomRight: [48, 48],
} as const;

describe("loadKtx2Texture against real KTX-Software output", () => {
    const SAMPLEABLE = GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST;

    it("places BC7 blocks such that every quadrant samples to its exact source colour", async () => {
        if (!device) return;
        const renderer = createTextureRenderer(device, Q, Q);
        try {
            const texture = await loadChecked(device, join(ASSETS, "quad-bc7.ktx2"));
            expect(texture.format).toBe("bc7-rgba-unorm");
            expect(texture.mipLevelCount).toBe(7);

            const px = await renderer.sample(texture, 0);
            expect(pixelAt(px, Q, ...QUADRANT.topLeft)).toEqual([255, 0, 0]);
            expect(pixelAt(px, Q, ...QUADRANT.topRight)).toEqual([0, 255, 0]);
            expect(pixelAt(px, Q, ...QUADRANT.bottomLeft)).toEqual([0, 0, 255]);
            expect(pixelAt(px, Q, ...QUADRANT.bottomRight)).toEqual([255, 255, 255]);
        } finally {
            renderer.destroy();
        }
    });

    it("uploads the mip chain in the right order, not reversed", async () => {
        if (!device) return;
        // The decisive check. Level 0 is four distinct quadrants; level 6 is 1x1,
        // the average of all four (~mid grey). If the chain were uploaded
        // reversed — or off by one — these two observations swap, and both
        // assertions fail. Structural tests cannot see this at all: every level
        // is exactly the size the loader expects either way.
        const renderer = createTextureRenderer(device, Q, Q);
        try {
            const texture = await loadChecked(device, join(ASSETS, "quad-bc7.ktx2"));

            const base = await renderer.sample(texture, 0);
            const corners = [
                pixelAt(base, Q, ...QUADRANT.topLeft),
                pixelAt(base, Q, ...QUADRANT.topRight),
                pixelAt(base, Q, ...QUADRANT.bottomLeft),
                pixelAt(base, Q, ...QUADRANT.bottomRight),
            ];
            expect(new Set(corners.map((c) => c.join(","))).size).toBe(4); // all distinct

            // The 1x1 tail: uniform, and near the average of the four quadrants
            // ((255+0+0+255)/4 = 127.5 per channel). Tolerance here is real —
            // this is a resample, not a flat block.
            const tail = await renderer.sample(texture, texture.mipLevelCount - 1);
            const [r, g, b] = pixelAt(tail, Q, 32, 32);
            expect(r).toBeGreaterThan(96);
            expect(r).toBeLessThan(160);
            expect(g).toBeGreaterThan(96);
            expect(g).toBeLessThan(160);
            expect(b).toBeGreaterThan(96);
            expect(b).toBeLessThan(160);
            // Uniform across the whole 1x1 level, wherever it is sampled.
            expect(pixelAt(tail, Q, 4, 60)).toEqual([r, g, b]);
        } finally {
            renderer.destroy();
        }
    });

    it("decompresses zstd to bytes identical to the uncompressed file", async () => {
        if (!device) return;
        // Supercompression is lossless, so this is an exact-equality test across
        // every mip level: anything other than a perfect match is a zstd bug,
        // and comparing full buffers catches a partial decompression that a
        // handful of sample points would miss.
        const renderer = createTextureRenderer(device, Q, Q);
        try {
            const plain = await loadChecked(device, join(ASSETS, "quad-bc7.ktx2"));
            const zstd = await loadChecked(device, join(ASSETS, "quad-bc7-zstd.ktx2"));
            expect(zstd.mipLevelCount).toBe(plain.mipLevelCount);

            for (let level = 0; level < plain.mipLevelCount; level++) {
                const a = await renderer.sample(plain, level);
                const b = await renderer.sample(zstd, level);
                expect(Buffer.from(b)).toEqual(Buffer.from(a));
            }
        } finally {
            renderer.destroy();
        }
    });

    it("loads real BC5 and BC1 files and samples them correctly", async () => {
        if (!device) return;
        const renderer = createTextureRenderer(device, Q, Q);
        try {
            // BC5 is two-channel — the format normal maps ship in, where the
            // shader reconstructs Z from X and Y. B always reads 0.
            //
            // The channel packing is worth stating because it is not the obvious
            // one: `ktx transcode --target bc5` maps **R -> R and A -> G**, the
            // normal-map convention, *not* R -> R and G -> G. The fixture is
            // opaque, so G reads 255 in every quadrant and only R carries
            // position here. That still distinguishes the red/white quadrants
            // from the green/blue ones; the full four-way positional proof is
            // the BC7 test above, which is the one that needs it.
            const bc5 = await loadChecked(device, join(ASSETS, "quad-bc5.ktx2"));
            expect(bc5.format).toBe("bc5-rg-unorm");
            const p5 = await renderer.sample(bc5, 0);
            expect(pixelAt(p5, Q, ...QUADRANT.topLeft)).toEqual([255, 255, 0]); // red   -> R 255
            expect(pixelAt(p5, Q, ...QUADRANT.topRight)).toEqual([0, 255, 0]); //  green -> R 0
            expect(pixelAt(p5, Q, ...QUADRANT.bottomLeft)).toEqual([0, 255, 0]); // blue -> R 0
            expect(pixelAt(p5, Q, ...QUADRANT.bottomRight)).toEqual([255, 255, 0]); // white -> R 255

            // The fixture is BC1_RGB_UNORM_BLOCK — the RGB spelling, which wgpu
            // has no separate format for, so it maps onto the RGBA one. These
            // primaries are exact under 565 quantisation.
            const bc1 = await loadChecked(device, join(ASSETS, "quad-bc1.ktx2"));
            expect(bc1.format).toBe("bc1-rgba-unorm");
            const p1 = await renderer.sample(bc1, 0);
            expect(pixelAt(p1, Q, ...QUADRANT.topLeft)).toEqual([255, 0, 0]);
            expect(pixelAt(p1, Q, ...QUADRANT.topRight)).toEqual([0, 255, 0]);
            expect(pixelAt(p1, Q, ...QUADRANT.bottomLeft)).toEqual([0, 0, 255]);
            expect(pixelAt(p1, Q, ...QUADRANT.bottomRight)).toEqual([255, 255, 255]);
        } finally {
            renderer.destroy();
        }
    });

    it("produces a sampleable texture with the default usage flags", async () => {
        if (!device) return;
        // The default is TEXTURE_BINDING | COPY_DST, so a caller that passes no
        // options gets something bindable — worth pinning, since every test
        // above would still pass if the default were wrong and the tests were
        // the only thing setting usage explicitly.
        const texture = await loadKtx2Texture(device, join(ASSETS, "quad-bc7.ktx2"));
        expect(texture.usage & GPUTextureUsage.TEXTURE_BINDING).toBeTruthy();
        expect(SAMPLEABLE & GPUTextureUsage.TEXTURE_BINDING).toBeTruthy();
    });
});
