// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./metis-native.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-android-arm64')
        const bindingPackageVersion = require('metis-native-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./metis-native.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-android-arm-eabi')
        const bindingPackageVersion = require('metis-native-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./metis-native.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-win32-x64-gnu')
        const bindingPackageVersion = require('metis-native-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./metis-native.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-win32-x64-msvc')
        const bindingPackageVersion = require('metis-native-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./metis-native.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-win32-ia32-msvc')
        const bindingPackageVersion = require('metis-native-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./metis-native.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-win32-arm64-msvc')
        const bindingPackageVersion = require('metis-native-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./metis-native.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('metis-native-darwin-universal')
      const bindingPackageVersion = require('metis-native-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./metis-native.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-darwin-x64')
        const bindingPackageVersion = require('metis-native-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./metis-native.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-darwin-arm64')
        const bindingPackageVersion = require('metis-native-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./metis-native.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-freebsd-x64')
        const bindingPackageVersion = require('metis-native-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./metis-native.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-freebsd-arm64')
        const bindingPackageVersion = require('metis-native-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./metis-native.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-x64-musl')
          const bindingPackageVersion = require('metis-native-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./metis-native.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-x64-gnu')
          const bindingPackageVersion = require('metis-native-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./metis-native.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-arm64-musl')
          const bindingPackageVersion = require('metis-native-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./metis-native.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-arm64-gnu')
          const bindingPackageVersion = require('metis-native-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./metis-native.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-arm-musleabihf')
          const bindingPackageVersion = require('metis-native-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./metis-native.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-arm-gnueabihf')
          const bindingPackageVersion = require('metis-native-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./metis-native.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-loong64-musl')
          const bindingPackageVersion = require('metis-native-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./metis-native.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-loong64-gnu')
          const bindingPackageVersion = require('metis-native-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./metis-native.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-riscv64-musl')
          const bindingPackageVersion = require('metis-native-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./metis-native.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('metis-native-linux-riscv64-gnu')
          const bindingPackageVersion = require('metis-native-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./metis-native.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-linux-ppc64-gnu')
        const bindingPackageVersion = require('metis-native-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./metis-native.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-linux-s390x-gnu')
        const bindingPackageVersion = require('metis-native-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./metis-native.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-openharmony-arm64')
        const bindingPackageVersion = require('metis-native-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./metis-native.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-openharmony-x64')
        const bindingPackageVersion = require('metis-native-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./metis-native.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('metis-native-openharmony-arm')
        const bindingPackageVersion = require('metis-native-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./metis-native.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = require('metis-native-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err
      return cur
    })
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.GpuAdapter = nativeBinding.GpuAdapter
module.exports.GpuBindGroup = nativeBinding.GpuBindGroup
module.exports.GpuBindGroupLayout = nativeBinding.GpuBindGroupLayout
module.exports.GpuBuffer = nativeBinding.GpuBuffer
module.exports.GpuCommandBuffer = nativeBinding.GpuCommandBuffer
module.exports.GpuCommandEncoder = nativeBinding.GpuCommandEncoder
module.exports.GpuComputePassEncoder = nativeBinding.GpuComputePassEncoder
module.exports.GpuComputePipeline = nativeBinding.GpuComputePipeline
module.exports.GpuDevice = nativeBinding.GpuDevice
module.exports.GpuPipelineLayout = nativeBinding.GpuPipelineLayout
module.exports.GpuQuerySet = nativeBinding.GpuQuerySet
module.exports.GpuQueue = nativeBinding.GpuQueue
module.exports.GpuRenderPassEncoder = nativeBinding.GpuRenderPassEncoder
module.exports.GpuRenderPipeline = nativeBinding.GpuRenderPipeline
module.exports.GpuSampler = nativeBinding.GpuSampler
module.exports.GpuShaderModule = nativeBinding.GpuShaderModule
module.exports.GpuSupportedFeatures = nativeBinding.GpuSupportedFeatures
module.exports.GpuSurface = nativeBinding.GpuSurface
module.exports.GpuSurfaceTexture = nativeBinding.GpuSurfaceTexture
module.exports.GpuTexture = nativeBinding.GpuTexture
module.exports.GpuTextureView = nativeBinding.GpuTextureView
module.exports.SdlCursor = nativeBinding.SdlCursor
module.exports.SdlGamepad = nativeBinding.SdlGamepad
module.exports.SdlJoystick = nativeBinding.SdlJoystick
module.exports.SdlKeyboardState = nativeBinding.SdlKeyboardState
module.exports.SdlWindow = nativeBinding.SdlWindow
module.exports.VectorContext = nativeBinding.VectorContext
module.exports.createSurface = nativeBinding.createSurface
module.exports.enumerateAdapters = nativeBinding.enumerateAdapters
module.exports.GPUBufferUsage = nativeBinding.GPUBufferUsage
module.exports.GpuBufferUsage = nativeBinding.GpuBufferUsage
module.exports.GPUColorWrite = nativeBinding.GPUColorWrite
module.exports.GpuColorWrite = nativeBinding.GpuColorWrite
module.exports.GPUMapMode = nativeBinding.GPUMapMode
module.exports.GpuMapMode = nativeBinding.GpuMapMode
module.exports.GPUShaderStage = nativeBinding.GPUShaderStage
module.exports.GpuShaderStage = nativeBinding.GpuShaderStage
module.exports.GPUTextureUsage = nativeBinding.GPUTextureUsage
module.exports.GpuTextureUsage = nativeBinding.GpuTextureUsage
module.exports.ImageColorSpace = nativeBinding.ImageColorSpace
module.exports.loadImageTexture = nativeBinding.loadImageTexture
module.exports.readTexturePixels = nativeBinding.readTexturePixels
module.exports.requestAdapter = nativeBinding.requestAdapter
module.exports.requestAdapterForWindow = nativeBinding.requestAdapterForWindow
module.exports.savePixelsToFile = nativeBinding.savePixelsToFile
module.exports.saveTextureToFile = nativeBinding.saveTextureToFile
module.exports.sdlCaptureMouse = nativeBinding.sdlCaptureMouse
module.exports.sdlCreateSystemCursor = nativeBinding.sdlCreateSystemCursor
module.exports.sdlCreateWindow = nativeBinding.sdlCreateWindow
module.exports.sdlCursorVisible = nativeBinding.sdlCursorVisible
module.exports.SdlEventType = nativeBinding.SdlEventType
module.exports.SdlGamepadAxis = nativeBinding.SdlGamepadAxis
module.exports.SdlGamepadButton = nativeBinding.SdlGamepadButton
module.exports.sdlGamepadEventsEnabled = nativeBinding.sdlGamepadEventsEnabled
module.exports.sdlGetCursor = nativeBinding.sdlGetCursor
module.exports.sdlGetDefaultCursor = nativeBinding.sdlGetDefaultCursor
module.exports.sdlGetError = nativeBinding.sdlGetError
module.exports.sdlGetGamepadNameForId = nativeBinding.sdlGetGamepadNameForId
module.exports.sdlGetGamepads = nativeBinding.sdlGetGamepads
module.exports.sdlGetGamepadTypeForId = nativeBinding.sdlGetGamepadTypeForId
module.exports.sdlGetGlobalMouseState = nativeBinding.sdlGetGlobalMouseState
module.exports.sdlGetHint = nativeBinding.sdlGetHint
module.exports.sdlGetJoystickNameForId = nativeBinding.sdlGetJoystickNameForId
module.exports.sdlGetJoysticks = nativeBinding.sdlGetJoysticks
module.exports.sdlGetJoystickTypeForId = nativeBinding.sdlGetJoystickTypeForId
module.exports.sdlGetKeyboardState = nativeBinding.sdlGetKeyboardState
module.exports.sdlGetKeyFromName = nativeBinding.sdlGetKeyFromName
module.exports.sdlGetKeyFromScancode = nativeBinding.sdlGetKeyFromScancode
module.exports.sdlGetKeyName = nativeBinding.sdlGetKeyName
module.exports.sdlGetModState = nativeBinding.sdlGetModState
module.exports.sdlGetMouseState = nativeBinding.sdlGetMouseState
module.exports.sdlGetPerformanceCounter = nativeBinding.sdlGetPerformanceCounter
module.exports.sdlGetPerformanceFrequency = nativeBinding.sdlGetPerformanceFrequency
module.exports.sdlGetRelativeMouseMode = nativeBinding.sdlGetRelativeMouseMode
module.exports.sdlGetRelativeMouseState = nativeBinding.sdlGetRelativeMouseState
module.exports.sdlGetScancodeFromKey = nativeBinding.sdlGetScancodeFromKey
module.exports.sdlGetScancodeFromName = nativeBinding.sdlGetScancodeFromName
module.exports.sdlGetScancodeName = nativeBinding.sdlGetScancodeName
module.exports.sdlGetTicks = nativeBinding.sdlGetTicks
module.exports.sdlHasGamepad = nativeBinding.sdlHasGamepad
module.exports.sdlHasJoystick = nativeBinding.sdlHasJoystick
module.exports.sdlHideCursor = nativeBinding.sdlHideCursor
module.exports.sdlInit = nativeBinding.sdlInit
module.exports.SdlInitFlag = nativeBinding.SdlInitFlag
module.exports.sdlIsGamepad = nativeBinding.sdlIsGamepad
module.exports.SdlJoyHat = nativeBinding.SdlJoyHat
module.exports.sdlJoystickEventsEnabled = nativeBinding.sdlJoystickEventsEnabled
module.exports.SdlKeycode = nativeBinding.SdlKeycode
module.exports.SdlKeymod = nativeBinding.SdlKeymod
module.exports.sdlLockJoysticks = nativeBinding.sdlLockJoysticks
module.exports.sdlLog = nativeBinding.sdlLog
module.exports.sdlLogMessage = nativeBinding.sdlLogMessage
module.exports.SdlMouseButton = nativeBinding.SdlMouseButton
module.exports.SdlMouseButtonMask = nativeBinding.SdlMouseButtonMask
module.exports.sdlOpenGamepad = nativeBinding.sdlOpenGamepad
module.exports.sdlOpenJoystick = nativeBinding.sdlOpenJoystick
module.exports.sdlPollEvents = nativeBinding.sdlPollEvents
module.exports.SdlPowerState = nativeBinding.SdlPowerState
module.exports.sdlPumpEvents = nativeBinding.sdlPumpEvents
module.exports.sdlQuit = nativeBinding.sdlQuit
module.exports.sdlResetKeyboard = nativeBinding.sdlResetKeyboard
module.exports.SdlScancode = nativeBinding.SdlScancode
module.exports.SdlSensorType = nativeBinding.SdlSensorType
module.exports.sdlSetCursor = nativeBinding.sdlSetCursor
module.exports.sdlSetGamepadEventsEnabled = nativeBinding.sdlSetGamepadEventsEnabled
module.exports.sdlSetHint = nativeBinding.sdlSetHint
module.exports.sdlSetJoystickEventsEnabled = nativeBinding.sdlSetJoystickEventsEnabled
module.exports.sdlSetLogPriority = nativeBinding.sdlSetLogPriority
module.exports.sdlSetModState = nativeBinding.sdlSetModState
module.exports.sdlSetRelativeMouseMode = nativeBinding.sdlSetRelativeMouseMode
module.exports.sdlShowCursor = nativeBinding.sdlShowCursor
module.exports.sdlStartTextInput = nativeBinding.sdlStartTextInput
module.exports.sdlStopTextInput = nativeBinding.sdlStopTextInput
module.exports.SdlSystemCursor = nativeBinding.SdlSystemCursor
module.exports.sdlTextInputActive = nativeBinding.sdlTextInputActive
module.exports.sdlUnlockJoysticks = nativeBinding.sdlUnlockJoysticks
module.exports.sdlUpdateGamepads = nativeBinding.sdlUpdateGamepads
module.exports.sdlUpdateJoysticks = nativeBinding.sdlUpdateJoysticks
module.exports.sdlWarpMouseGlobal = nativeBinding.sdlWarpMouseGlobal
module.exports.sdlWarpMouseInWindow = nativeBinding.sdlWarpMouseInWindow
module.exports.SdlWindowFlag = nativeBinding.SdlWindowFlag
